package com.merck.catalog.admin.dao;

import com.merck.catalog.admin.model.TbCab003d;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCab003dMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB003D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int deleteByPrimaryKey(@Param("boardId") String boardId, @Param("postId") String postId, @Param("replyId") String replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB003D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int insert(TbCab003d record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB003D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    TbCab003d selectByPrimaryKey(@Param("boardId") String boardId, @Param("postId") String postId, @Param("replyId") String replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB003D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    List<TbCab003d> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB003D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int updateByPrimaryKey(TbCab003d record);
}