package com.merck.catalog.admin.dao;

import com.merck.catalog.admin.model.TbCab001m;
import java.util.List;

public interface TbCab001mMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int deleteByPrimaryKey(String boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int insert(TbCab001m record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    TbCab001m selectByPrimaryKey(String boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    List<TbCab001m> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int updateByPrimaryKey(TbCab001m record);
}