package com.merck.catalog.admin.dao;

import com.merck.catalog.admin.model.TbCaa001m;
import java.util.List;

public interface TbCaa001mMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int deleteByPrimaryKey(String catlgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int insert(TbCaa001m record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    TbCaa001m selectByPrimaryKey(String catlgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    List<TbCaa001m> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int updateByPrimaryKey(TbCaa001m record);
}