package com.merck.catalog.admin.dao;

import com.merck.catalog.admin.model.TbCab004d;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCab004dMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB004D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int deleteByPrimaryKey(@Param("boardId") String boardId, @Param("boardId1") String boardId1, @Param("taskDtlSeCd") String taskDtlSeCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB004D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int insert(TbCab004d record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB004D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    TbCab004d selectByPrimaryKey(@Param("boardId") String boardId, @Param("boardId1") String boardId1, @Param("taskDtlSeCd") String taskDtlSeCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB004D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    List<TbCab004d> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB004D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int updateByPrimaryKey(TbCab004d record);
}