package com.merck.catalog.admin.dao;

import com.merck.catalog.admin.model.TbCba001m;
import java.util.List;

public interface TbCba001mMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CBA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int deleteByPrimaryKey(String libryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CBA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int insert(TbCba001m record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CBA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    TbCba001m selectByPrimaryKey(String libryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CBA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    List<TbCba001m> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CBA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int updateByPrimaryKey(TbCba001m record);
}