package com.merck.catalog.admin.dao;

import com.merck.catalog.admin.model.TbSaa002d;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSaa002dMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAA002D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int deleteByPrimaryKey(@Param("cmmnCdId") String cmmnCdId, @Param("cmmnCd") String cmmnCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAA002D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int insert(TbSaa002d record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAA002D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    TbSaa002d selectByPrimaryKey(@Param("cmmnCdId") String cmmnCdId, @Param("cmmnCd") String cmmnCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAA002D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    List<TbSaa002d> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAA002D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int updateByPrimaryKey(TbSaa002d record);
}