package com.merck.catalog.admin.dao;

import com.merck.catalog.admin.model.TbSaa001m;
import java.util.List;

public interface TbSaa001mMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int deleteByPrimaryKey(String cmmnCdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int insert(TbSaa001m record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    TbSaa001m selectByPrimaryKey(String cmmnCdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    List<TbSaa001m> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAA001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int updateByPrimaryKey(TbSaa001m record);
}