package com.merck.catalog.admin.dao;

import com.merck.catalog.admin.model.TbSaf003d;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSaf003dMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAF003D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int deleteByPrimaryKey(@Param("catlgFileGrpId") String catlgFileGrpId, @Param("catlgFileId") String catlgFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAF003D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int insert(TbSaf003d record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAF003D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    TbSaf003d selectByPrimaryKey(@Param("catlgFileGrpId") String catlgFileGrpId, @Param("catlgFileId") String catlgFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAF003D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    List<TbSaf003d> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAF003D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int updateByPrimaryKey(TbSaf003d record);
}