package com.merck.catalog.admin.dao;

import com.merck.catalog.admin.model.TbSau001m;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSau001mMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAU001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int deleteByPrimaryKey(@Param("usrId") String usrId, @Param("pipaUsrId") String pipaUsrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAU001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int insert(TbSau001m record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAU001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    TbSau001m selectByPrimaryKey(@Param("usrId") String usrId, @Param("pipaUsrId") String pipaUsrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAU001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    List<TbSau001m> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAU001M
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int updateByPrimaryKey(TbSau001m record);
}