package com.merck.catalog.admin.dao;

import com.merck.catalog.admin.model.TbSau002d;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSau002dMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAU002D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int deleteByPrimaryKey(@Param("usrId") String usrId, @Param("udid") String udid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAU002D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int insert(TbSau002d record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAU002D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    TbSau002d selectByPrimaryKey(@Param("usrId") String usrId, @Param("udid") String udid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAU002D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    List<TbSau002d> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAU002D
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    int updateByPrimaryKey(TbSau002d record);
}