package com.merck.catalog.admin.model;

import java.util.Date;

public class TbCab001m {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.BOARD_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String boardNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.BOARD_DESC
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String boardDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.TASK_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String taskSeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.TASK_DTL_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String taskDtlSeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.BEGIN_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String beginDte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.END_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String endDte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.ATTCH_FILE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String attchFileYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.IMG_VIEWR_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String imgViewrYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.REPLY_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String replyYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.HIDDN_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String hiddnYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.DEL_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String delYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.BOARD_ID
     *
     * @return the value of TB_CAB001M.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.BOARD_ID
     *
     * @param boardId the value for TB_CAB001M.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setBoardId(String boardId) {
        this.boardId = boardId == null ? null : boardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.BOARD_NM
     *
     * @return the value of TB_CAB001M.BOARD_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getBoardNm() {
        return boardNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.BOARD_NM
     *
     * @param boardNm the value for TB_CAB001M.BOARD_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setBoardNm(String boardNm) {
        this.boardNm = boardNm == null ? null : boardNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.BOARD_DESC
     *
     * @return the value of TB_CAB001M.BOARD_DESC
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getBoardDesc() {
        return boardDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.BOARD_DESC
     *
     * @param boardDesc the value for TB_CAB001M.BOARD_DESC
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setBoardDesc(String boardDesc) {
        this.boardDesc = boardDesc == null ? null : boardDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.TASK_SE_CD
     *
     * @return the value of TB_CAB001M.TASK_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getTaskSeCd() {
        return taskSeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.TASK_SE_CD
     *
     * @param taskSeCd the value for TB_CAB001M.TASK_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setTaskSeCd(String taskSeCd) {
        this.taskSeCd = taskSeCd == null ? null : taskSeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.TASK_DTL_SE_CD
     *
     * @return the value of TB_CAB001M.TASK_DTL_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getTaskDtlSeCd() {
        return taskDtlSeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.TASK_DTL_SE_CD
     *
     * @param taskDtlSeCd the value for TB_CAB001M.TASK_DTL_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setTaskDtlSeCd(String taskDtlSeCd) {
        this.taskDtlSeCd = taskDtlSeCd == null ? null : taskDtlSeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.BEGIN_DTE
     *
     * @return the value of TB_CAB001M.BEGIN_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getBeginDte() {
        return beginDte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.BEGIN_DTE
     *
     * @param beginDte the value for TB_CAB001M.BEGIN_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setBeginDte(String beginDte) {
        this.beginDte = beginDte == null ? null : beginDte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.END_DTE
     *
     * @return the value of TB_CAB001M.END_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getEndDte() {
        return endDte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.END_DTE
     *
     * @param endDte the value for TB_CAB001M.END_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setEndDte(String endDte) {
        this.endDte = endDte == null ? null : endDte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.ATTCH_FILE_YN
     *
     * @return the value of TB_CAB001M.ATTCH_FILE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getAttchFileYn() {
        return attchFileYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.ATTCH_FILE_YN
     *
     * @param attchFileYn the value for TB_CAB001M.ATTCH_FILE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setAttchFileYn(String attchFileYn) {
        this.attchFileYn = attchFileYn == null ? null : attchFileYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.IMG_VIEWR_YN
     *
     * @return the value of TB_CAB001M.IMG_VIEWR_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getImgViewrYn() {
        return imgViewrYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.IMG_VIEWR_YN
     *
     * @param imgViewrYn the value for TB_CAB001M.IMG_VIEWR_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setImgViewrYn(String imgViewrYn) {
        this.imgViewrYn = imgViewrYn == null ? null : imgViewrYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.REPLY_YN
     *
     * @return the value of TB_CAB001M.REPLY_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getReplyYn() {
        return replyYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.REPLY_YN
     *
     * @param replyYn the value for TB_CAB001M.REPLY_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setReplyYn(String replyYn) {
        this.replyYn = replyYn == null ? null : replyYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.HIDDN_YN
     *
     * @return the value of TB_CAB001M.HIDDN_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getHiddnYn() {
        return hiddnYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.HIDDN_YN
     *
     * @param hiddnYn the value for TB_CAB001M.HIDDN_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setHiddnYn(String hiddnYn) {
        this.hiddnYn = hiddnYn == null ? null : hiddnYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.DEL_YN
     *
     * @return the value of TB_CAB001M.DEL_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getDelYn() {
        return delYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.DEL_YN
     *
     * @param delYn the value for TB_CAB001M.DEL_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setDelYn(String delYn) {
        this.delYn = delYn == null ? null : delYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.USE_YN
     *
     * @return the value of TB_CAB001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.USE_YN
     *
     * @param useYn the value for TB_CAB001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.REGIST_USR_ID
     *
     * @return the value of TB_CAB001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_CAB001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.REGIST_DT
     *
     * @return the value of TB_CAB001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.REGIST_DT
     *
     * @param registDt the value for TB_CAB001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.UPDT_ID
     *
     * @return the value of TB_CAB001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtId() {
        return updtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.UPDT_ID
     *
     * @param updtId the value for TB_CAB001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtId(String updtId) {
        this.updtId = updtId == null ? null : updtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB001M.UPDT_DT
     *
     * @return the value of TB_CAB001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB001M.UPDT_DT
     *
     * @param updtDt the value for TB_CAB001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }
}