package com.merck.catalog.admin.model;

import java.util.Date;

public class TbCab002d {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.POST_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.TITLE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String cn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.TASK_DTL_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String taskDtlSeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.CATGR_ID_GRP
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String catgrIdGrp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.CATLG_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String catlgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String imgFileGrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.ATTCH_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String attchFileGrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.HIDDN_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String hiddnYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.REPLY_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String replyYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.DEL_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String delYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB002D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.BOARD_ID
     *
     * @return the value of TB_CAB002D.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.BOARD_ID
     *
     * @param boardId the value for TB_CAB002D.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setBoardId(String boardId) {
        this.boardId = boardId == null ? null : boardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.POST_ID
     *
     * @return the value of TB_CAB002D.POST_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.POST_ID
     *
     * @param postId the value for TB_CAB002D.POST_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPostId(String postId) {
        this.postId = postId == null ? null : postId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.TITLE
     *
     * @return the value of TB_CAB002D.TITLE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.TITLE
     *
     * @param title the value for TB_CAB002D.TITLE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.CN
     *
     * @return the value of TB_CAB002D.CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCn() {
        return cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.CN
     *
     * @param cn the value for TB_CAB002D.CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCn(String cn) {
        this.cn = cn == null ? null : cn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.PASSWD
     *
     * @return the value of TB_CAB002D.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.PASSWD
     *
     * @param passwd the value for TB_CAB002D.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.TASK_DTL_SE_CD
     *
     * @return the value of TB_CAB002D.TASK_DTL_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getTaskDtlSeCd() {
        return taskDtlSeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.TASK_DTL_SE_CD
     *
     * @param taskDtlSeCd the value for TB_CAB002D.TASK_DTL_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setTaskDtlSeCd(String taskDtlSeCd) {
        this.taskDtlSeCd = taskDtlSeCd == null ? null : taskDtlSeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.CATGR_ID_GRP
     *
     * @return the value of TB_CAB002D.CATGR_ID_GRP
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCatgrIdGrp() {
        return catgrIdGrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.CATGR_ID_GRP
     *
     * @param catgrIdGrp the value for TB_CAB002D.CATGR_ID_GRP
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCatgrIdGrp(String catgrIdGrp) {
        this.catgrIdGrp = catgrIdGrp == null ? null : catgrIdGrp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.CATLG_ID
     *
     * @return the value of TB_CAB002D.CATLG_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCatlgId() {
        return catlgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.CATLG_ID
     *
     * @param catlgId the value for TB_CAB002D.CATLG_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCatlgId(String catlgId) {
        this.catlgId = catlgId == null ? null : catlgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.IMG_FILE_GRP_ID
     *
     * @return the value of TB_CAB002D.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getImgFileGrpId() {
        return imgFileGrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.IMG_FILE_GRP_ID
     *
     * @param imgFileGrpId the value for TB_CAB002D.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setImgFileGrpId(String imgFileGrpId) {
        this.imgFileGrpId = imgFileGrpId == null ? null : imgFileGrpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.ATTCH_FILE_GRP_ID
     *
     * @return the value of TB_CAB002D.ATTCH_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getAttchFileGrpId() {
        return attchFileGrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.ATTCH_FILE_GRP_ID
     *
     * @param attchFileGrpId the value for TB_CAB002D.ATTCH_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setAttchFileGrpId(String attchFileGrpId) {
        this.attchFileGrpId = attchFileGrpId == null ? null : attchFileGrpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.HIDDN_YN
     *
     * @return the value of TB_CAB002D.HIDDN_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getHiddnYn() {
        return hiddnYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.HIDDN_YN
     *
     * @param hiddnYn the value for TB_CAB002D.HIDDN_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setHiddnYn(String hiddnYn) {
        this.hiddnYn = hiddnYn == null ? null : hiddnYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.REPLY_YN
     *
     * @return the value of TB_CAB002D.REPLY_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getReplyYn() {
        return replyYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.REPLY_YN
     *
     * @param replyYn the value for TB_CAB002D.REPLY_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setReplyYn(String replyYn) {
        this.replyYn = replyYn == null ? null : replyYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.DEL_YN
     *
     * @return the value of TB_CAB002D.DEL_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getDelYn() {
        return delYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.DEL_YN
     *
     * @param delYn the value for TB_CAB002D.DEL_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setDelYn(String delYn) {
        this.delYn = delYn == null ? null : delYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.USE_YN
     *
     * @return the value of TB_CAB002D.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.USE_YN
     *
     * @param useYn the value for TB_CAB002D.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.REGIST_USR_ID
     *
     * @return the value of TB_CAB002D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_CAB002D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.REGIST_DT
     *
     * @return the value of TB_CAB002D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.REGIST_DT
     *
     * @param registDt the value for TB_CAB002D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.UPDT_ID
     *
     * @return the value of TB_CAB002D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtId() {
        return updtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.UPDT_ID
     *
     * @param updtId the value for TB_CAB002D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtId(String updtId) {
        this.updtId = updtId == null ? null : updtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB002D.UPDT_DT
     *
     * @return the value of TB_CAB002D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB002D.UPDT_DT
     *
     * @param updtDt the value for TB_CAB002D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }
}