package com.merck.catalog.admin.model;

import java.util.Date;

public class TbCab003d {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.POST_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.REPLY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.UPPER_REPLY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String upperReplyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String cn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.HIDDN_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String hiddnYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String imgFileGrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.ATTCH_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String attchFileGrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.DEL_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String delYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB003D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.BOARD_ID
     *
     * @return the value of TB_CAB003D.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.BOARD_ID
     *
     * @param boardId the value for TB_CAB003D.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setBoardId(String boardId) {
        this.boardId = boardId == null ? null : boardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.POST_ID
     *
     * @return the value of TB_CAB003D.POST_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.POST_ID
     *
     * @param postId the value for TB_CAB003D.POST_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPostId(String postId) {
        this.postId = postId == null ? null : postId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.REPLY_ID
     *
     * @return the value of TB_CAB003D.REPLY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.REPLY_ID
     *
     * @param replyId the value for TB_CAB003D.REPLY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setReplyId(String replyId) {
        this.replyId = replyId == null ? null : replyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.UPPER_REPLY_ID
     *
     * @return the value of TB_CAB003D.UPPER_REPLY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpperReplyId() {
        return upperReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.UPPER_REPLY_ID
     *
     * @param upperReplyId the value for TB_CAB003D.UPPER_REPLY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpperReplyId(String upperReplyId) {
        this.upperReplyId = upperReplyId == null ? null : upperReplyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.CN
     *
     * @return the value of TB_CAB003D.CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCn() {
        return cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.CN
     *
     * @param cn the value for TB_CAB003D.CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCn(String cn) {
        this.cn = cn == null ? null : cn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.HIDDN_YN
     *
     * @return the value of TB_CAB003D.HIDDN_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getHiddnYn() {
        return hiddnYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.HIDDN_YN
     *
     * @param hiddnYn the value for TB_CAB003D.HIDDN_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setHiddnYn(String hiddnYn) {
        this.hiddnYn = hiddnYn == null ? null : hiddnYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.PASSWD
     *
     * @return the value of TB_CAB003D.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.PASSWD
     *
     * @param passwd the value for TB_CAB003D.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.IMG_FILE_GRP_ID
     *
     * @return the value of TB_CAB003D.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getImgFileGrpId() {
        return imgFileGrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.IMG_FILE_GRP_ID
     *
     * @param imgFileGrpId the value for TB_CAB003D.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setImgFileGrpId(String imgFileGrpId) {
        this.imgFileGrpId = imgFileGrpId == null ? null : imgFileGrpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.ATTCH_FILE_GRP_ID
     *
     * @return the value of TB_CAB003D.ATTCH_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getAttchFileGrpId() {
        return attchFileGrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.ATTCH_FILE_GRP_ID
     *
     * @param attchFileGrpId the value for TB_CAB003D.ATTCH_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setAttchFileGrpId(String attchFileGrpId) {
        this.attchFileGrpId = attchFileGrpId == null ? null : attchFileGrpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.DEL_YN
     *
     * @return the value of TB_CAB003D.DEL_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getDelYn() {
        return delYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.DEL_YN
     *
     * @param delYn the value for TB_CAB003D.DEL_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setDelYn(String delYn) {
        this.delYn = delYn == null ? null : delYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.REGIST_USR_ID
     *
     * @return the value of TB_CAB003D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_CAB003D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.REGIST_DT
     *
     * @return the value of TB_CAB003D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.REGIST_DT
     *
     * @param registDt the value for TB_CAB003D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.UPDT_ID
     *
     * @return the value of TB_CAB003D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtId() {
        return updtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.UPDT_ID
     *
     * @param updtId the value for TB_CAB003D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtId(String updtId) {
        this.updtId = updtId == null ? null : updtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB003D.UPDT_DT
     *
     * @return the value of TB_CAB003D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB003D.UPDT_DT
     *
     * @param updtDt the value for TB_CAB003D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }
}