package com.merck.catalog.admin.model;

import java.util.Date;

public class TbCaa001m {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.CATLG_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String catlgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.CATLG_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String catlgNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.CATGR_ID_GRP
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String catgrIdGrp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.LANG_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String langSeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.VER_INFO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String verInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.KEYWD_VAL_GRP
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String keywdValGrp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.ISSUE_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String issueDte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.SIMPL_CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String simplCn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.DETL_CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String detlCn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.TEL_MANG_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String telMangUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.EMAIL_MANG_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String emailMangUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.DOWNLD_CNT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Long downldCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.LIKE_CNT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Long likeCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String imgFileGrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.CATLG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String catlgFileGrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAA001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.CATLG_ID
     *
     * @return the value of TB_CAA001M.CATLG_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCatlgId() {
        return catlgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.CATLG_ID
     *
     * @param catlgId the value for TB_CAA001M.CATLG_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCatlgId(String catlgId) {
        this.catlgId = catlgId == null ? null : catlgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.CATLG_NM
     *
     * @return the value of TB_CAA001M.CATLG_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCatlgNm() {
        return catlgNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.CATLG_NM
     *
     * @param catlgNm the value for TB_CAA001M.CATLG_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCatlgNm(String catlgNm) {
        this.catlgNm = catlgNm == null ? null : catlgNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.CATGR_ID_GRP
     *
     * @return the value of TB_CAA001M.CATGR_ID_GRP
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCatgrIdGrp() {
        return catgrIdGrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.CATGR_ID_GRP
     *
     * @param catgrIdGrp the value for TB_CAA001M.CATGR_ID_GRP
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCatgrIdGrp(String catgrIdGrp) {
        this.catgrIdGrp = catgrIdGrp == null ? null : catgrIdGrp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.LANG_SE_CD
     *
     * @return the value of TB_CAA001M.LANG_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getLangSeCd() {
        return langSeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.LANG_SE_CD
     *
     * @param langSeCd the value for TB_CAA001M.LANG_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setLangSeCd(String langSeCd) {
        this.langSeCd = langSeCd == null ? null : langSeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.VER_INFO
     *
     * @return the value of TB_CAA001M.VER_INFO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getVerInfo() {
        return verInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.VER_INFO
     *
     * @param verInfo the value for TB_CAA001M.VER_INFO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setVerInfo(String verInfo) {
        this.verInfo = verInfo == null ? null : verInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.KEYWD_VAL_GRP
     *
     * @return the value of TB_CAA001M.KEYWD_VAL_GRP
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getKeywdValGrp() {
        return keywdValGrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.KEYWD_VAL_GRP
     *
     * @param keywdValGrp the value for TB_CAA001M.KEYWD_VAL_GRP
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setKeywdValGrp(String keywdValGrp) {
        this.keywdValGrp = keywdValGrp == null ? null : keywdValGrp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.ISSUE_DTE
     *
     * @return the value of TB_CAA001M.ISSUE_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getIssueDte() {
        return issueDte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.ISSUE_DTE
     *
     * @param issueDte the value for TB_CAA001M.ISSUE_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setIssueDte(String issueDte) {
        this.issueDte = issueDte == null ? null : issueDte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.SIMPL_CN
     *
     * @return the value of TB_CAA001M.SIMPL_CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getSimplCn() {
        return simplCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.SIMPL_CN
     *
     * @param simplCn the value for TB_CAA001M.SIMPL_CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setSimplCn(String simplCn) {
        this.simplCn = simplCn == null ? null : simplCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.DETL_CN
     *
     * @return the value of TB_CAA001M.DETL_CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getDetlCn() {
        return detlCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.DETL_CN
     *
     * @param detlCn the value for TB_CAA001M.DETL_CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setDetlCn(String detlCn) {
        this.detlCn = detlCn == null ? null : detlCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.TEL_MANG_USR_ID
     *
     * @return the value of TB_CAA001M.TEL_MANG_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getTelMangUsrId() {
        return telMangUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.TEL_MANG_USR_ID
     *
     * @param telMangUsrId the value for TB_CAA001M.TEL_MANG_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setTelMangUsrId(String telMangUsrId) {
        this.telMangUsrId = telMangUsrId == null ? null : telMangUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.EMAIL_MANG_USR_ID
     *
     * @return the value of TB_CAA001M.EMAIL_MANG_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getEmailMangUsrId() {
        return emailMangUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.EMAIL_MANG_USR_ID
     *
     * @param emailMangUsrId the value for TB_CAA001M.EMAIL_MANG_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setEmailMangUsrId(String emailMangUsrId) {
        this.emailMangUsrId = emailMangUsrId == null ? null : emailMangUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.DOWNLD_CNT
     *
     * @return the value of TB_CAA001M.DOWNLD_CNT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Long getDownldCnt() {
        return downldCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.DOWNLD_CNT
     *
     * @param downldCnt the value for TB_CAA001M.DOWNLD_CNT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setDownldCnt(Long downldCnt) {
        this.downldCnt = downldCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.LIKE_CNT
     *
     * @return the value of TB_CAA001M.LIKE_CNT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Long getLikeCnt() {
        return likeCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.LIKE_CNT
     *
     * @param likeCnt the value for TB_CAA001M.LIKE_CNT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setLikeCnt(Long likeCnt) {
        this.likeCnt = likeCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.IMG_FILE_GRP_ID
     *
     * @return the value of TB_CAA001M.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getImgFileGrpId() {
        return imgFileGrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.IMG_FILE_GRP_ID
     *
     * @param imgFileGrpId the value for TB_CAA001M.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setImgFileGrpId(String imgFileGrpId) {
        this.imgFileGrpId = imgFileGrpId == null ? null : imgFileGrpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.CATLG_FILE_GRP_ID
     *
     * @return the value of TB_CAA001M.CATLG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCatlgFileGrpId() {
        return catlgFileGrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.CATLG_FILE_GRP_ID
     *
     * @param catlgFileGrpId the value for TB_CAA001M.CATLG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCatlgFileGrpId(String catlgFileGrpId) {
        this.catlgFileGrpId = catlgFileGrpId == null ? null : catlgFileGrpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.USE_YN
     *
     * @return the value of TB_CAA001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.USE_YN
     *
     * @param useYn the value for TB_CAA001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.REGIST_USR_ID
     *
     * @return the value of TB_CAA001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_CAA001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.REGIST_DT
     *
     * @return the value of TB_CAA001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.REGIST_DT
     *
     * @param registDt the value for TB_CAA001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.UPDT_ID
     *
     * @return the value of TB_CAA001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtId() {
        return updtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.UPDT_ID
     *
     * @param updtId the value for TB_CAA001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtId(String updtId) {
        this.updtId = updtId == null ? null : updtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAA001M.UPDT_DT
     *
     * @return the value of TB_CAA001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAA001M.UPDT_DT
     *
     * @param updtDt the value for TB_CAA001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }
}