package com.merck.catalog.admin.model;

import java.util.Date;

public class TbCab004d {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.BOARD_ID1
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String boardId1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.TASK_DTL_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String taskDtlSeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.MANG_DEPT_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangDeptNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.MANG_USR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangUsrNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.EMAIL_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String emailAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.COMP_TEL_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String compTelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.PHONE_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.BOARD_ID
     *
     * @return the value of TB_CAB004D.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.BOARD_ID
     *
     * @param boardId the value for TB_CAB004D.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setBoardId(String boardId) {
        this.boardId = boardId == null ? null : boardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.BOARD_ID1
     *
     * @return the value of TB_CAB004D.BOARD_ID1
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getBoardId1() {
        return boardId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.BOARD_ID1
     *
     * @param boardId1 the value for TB_CAB004D.BOARD_ID1
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setBoardId1(String boardId1) {
        this.boardId1 = boardId1 == null ? null : boardId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.TASK_DTL_SE_CD
     *
     * @return the value of TB_CAB004D.TASK_DTL_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getTaskDtlSeCd() {
        return taskDtlSeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.TASK_DTL_SE_CD
     *
     * @param taskDtlSeCd the value for TB_CAB004D.TASK_DTL_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setTaskDtlSeCd(String taskDtlSeCd) {
        this.taskDtlSeCd = taskDtlSeCd == null ? null : taskDtlSeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.MANG_DEPT_NM
     *
     * @return the value of TB_CAB004D.MANG_DEPT_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangDeptNm() {
        return mangDeptNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.MANG_DEPT_NM
     *
     * @param mangDeptNm the value for TB_CAB004D.MANG_DEPT_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangDeptNm(String mangDeptNm) {
        this.mangDeptNm = mangDeptNm == null ? null : mangDeptNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.MANG_USR_NM
     *
     * @return the value of TB_CAB004D.MANG_USR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangUsrNm() {
        return mangUsrNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.MANG_USR_NM
     *
     * @param mangUsrNm the value for TB_CAB004D.MANG_USR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangUsrNm(String mangUsrNm) {
        this.mangUsrNm = mangUsrNm == null ? null : mangUsrNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.EMAIL_ADDR
     *
     * @return the value of TB_CAB004D.EMAIL_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getEmailAddr() {
        return emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.EMAIL_ADDR
     *
     * @param emailAddr the value for TB_CAB004D.EMAIL_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr == null ? null : emailAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.COMP_TEL_NO
     *
     * @return the value of TB_CAB004D.COMP_TEL_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCompTelNo() {
        return compTelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.COMP_TEL_NO
     *
     * @param compTelNo the value for TB_CAB004D.COMP_TEL_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCompTelNo(String compTelNo) {
        this.compTelNo = compTelNo == null ? null : compTelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.PHONE_NO
     *
     * @return the value of TB_CAB004D.PHONE_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.PHONE_NO
     *
     * @param phoneNo the value for TB_CAB004D.PHONE_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.REGIST_USR_ID
     *
     * @return the value of TB_CAB004D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_CAB004D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.REGIST_DT
     *
     * @return the value of TB_CAB004D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.REGIST_DT
     *
     * @param registDt the value for TB_CAB004D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.UPDT_ID
     *
     * @return the value of TB_CAB004D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtId() {
        return updtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.UPDT_ID
     *
     * @param updtId the value for TB_CAB004D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtId(String updtId) {
        this.updtId = updtId == null ? null : updtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.UPDT_DT
     *
     * @return the value of TB_CAB004D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.UPDT_DT
     *
     * @param updtDt the value for TB_CAB004D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }
}