package com.merck.catalog.admin.model;

import java.util.Date;

public class TbCbb001m {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBB001M.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String usrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBB001M.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBB001M.POST_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBB001M.CONFM_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String confmYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBB001M.SHOW_BEGIN_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String showBeginDte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBB001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBB001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBB001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBB001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBB001M.USR_ID
     *
     * @return the value of TB_CBB001M.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBB001M.USR_ID
     *
     * @param usrId the value for TB_CBB001M.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUsrId(String usrId) {
        this.usrId = usrId == null ? null : usrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBB001M.BOARD_ID
     *
     * @return the value of TB_CBB001M.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBB001M.BOARD_ID
     *
     * @param boardId the value for TB_CBB001M.BOARD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setBoardId(String boardId) {
        this.boardId = boardId == null ? null : boardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBB001M.POST_ID
     *
     * @return the value of TB_CBB001M.POST_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBB001M.POST_ID
     *
     * @param postId the value for TB_CBB001M.POST_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPostId(String postId) {
        this.postId = postId == null ? null : postId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBB001M.CONFM_YN
     *
     * @return the value of TB_CBB001M.CONFM_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getConfmYn() {
        return confmYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBB001M.CONFM_YN
     *
     * @param confmYn the value for TB_CBB001M.CONFM_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setConfmYn(String confmYn) {
        this.confmYn = confmYn == null ? null : confmYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBB001M.SHOW_BEGIN_DTE
     *
     * @return the value of TB_CBB001M.SHOW_BEGIN_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getShowBeginDte() {
        return showBeginDte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBB001M.SHOW_BEGIN_DTE
     *
     * @param showBeginDte the value for TB_CBB001M.SHOW_BEGIN_DTE
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setShowBeginDte(String showBeginDte) {
        this.showBeginDte = showBeginDte == null ? null : showBeginDte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBB001M.REGIST_USR_ID
     *
     * @return the value of TB_CBB001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBB001M.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_CBB001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBB001M.REGIST_DT
     *
     * @return the value of TB_CBB001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBB001M.REGIST_DT
     *
     * @param registDt the value for TB_CBB001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBB001M.UPDT_ID
     *
     * @return the value of TB_CBB001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtId() {
        return updtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBB001M.UPDT_ID
     *
     * @param updtId the value for TB_CBB001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtId(String updtId) {
        this.updtId = updtId == null ? null : updtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBB001M.UPDT_DT
     *
     * @return the value of TB_CBB001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBB001M.UPDT_DT
     *
     * @param updtDt the value for TB_CBB001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }
}