package com.merck.catalog.admin.model;

import java.util.Date;

public class TbCba001m {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBA001M.LIBRY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String libryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBA001M.LIBRY_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String libryNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBA001M.UPPER_LIBRY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String upperLibryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBA001M.CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String cn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBA001M.CATLG_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String catlgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBA001M.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String imgFileGrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBA001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBA001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBA001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBA001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CBA001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBA001M.LIBRY_ID
     *
     * @return the value of TB_CBA001M.LIBRY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getLibryId() {
        return libryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBA001M.LIBRY_ID
     *
     * @param libryId the value for TB_CBA001M.LIBRY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setLibryId(String libryId) {
        this.libryId = libryId == null ? null : libryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBA001M.LIBRY_NM
     *
     * @return the value of TB_CBA001M.LIBRY_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getLibryNm() {
        return libryNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBA001M.LIBRY_NM
     *
     * @param libryNm the value for TB_CBA001M.LIBRY_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setLibryNm(String libryNm) {
        this.libryNm = libryNm == null ? null : libryNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBA001M.UPPER_LIBRY_ID
     *
     * @return the value of TB_CBA001M.UPPER_LIBRY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpperLibryId() {
        return upperLibryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBA001M.UPPER_LIBRY_ID
     *
     * @param upperLibryId the value for TB_CBA001M.UPPER_LIBRY_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpperLibryId(String upperLibryId) {
        this.upperLibryId = upperLibryId == null ? null : upperLibryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBA001M.CN
     *
     * @return the value of TB_CBA001M.CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCn() {
        return cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBA001M.CN
     *
     * @param cn the value for TB_CBA001M.CN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCn(String cn) {
        this.cn = cn == null ? null : cn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBA001M.CATLG_ID
     *
     * @return the value of TB_CBA001M.CATLG_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCatlgId() {
        return catlgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBA001M.CATLG_ID
     *
     * @param catlgId the value for TB_CBA001M.CATLG_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCatlgId(String catlgId) {
        this.catlgId = catlgId == null ? null : catlgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBA001M.IMG_FILE_GRP_ID
     *
     * @return the value of TB_CBA001M.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getImgFileGrpId() {
        return imgFileGrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBA001M.IMG_FILE_GRP_ID
     *
     * @param imgFileGrpId the value for TB_CBA001M.IMG_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setImgFileGrpId(String imgFileGrpId) {
        this.imgFileGrpId = imgFileGrpId == null ? null : imgFileGrpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBA001M.USE_YN
     *
     * @return the value of TB_CBA001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBA001M.USE_YN
     *
     * @param useYn the value for TB_CBA001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBA001M.REGIST_USR_ID
     *
     * @return the value of TB_CBA001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBA001M.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_CBA001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBA001M.REGIST_DT
     *
     * @return the value of TB_CBA001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBA001M.REGIST_DT
     *
     * @param registDt the value for TB_CBA001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBA001M.UPDT_ID
     *
     * @return the value of TB_CBA001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtId() {
        return updtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBA001M.UPDT_ID
     *
     * @param updtId the value for TB_CBA001M.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtId(String updtId) {
        this.updtId = updtId == null ? null : updtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CBA001M.UPDT_DT
     *
     * @return the value of TB_CBA001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CBA001M.UPDT_DT
     *
     * @param updtDt the value for TB_CBA001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }
}