package com.merck.catalog.admin.model;

import java.util.Date;

public class TbSaf001d {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.ATTCH_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String attchFileGrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.ATTCH_FILE_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String attchFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.FILE_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String fileNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.FILE_EXT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String fileExt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.FILE_LENTH
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Long fileLenth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.FILE_PATH
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.FILE_URL
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.SORT_SN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Long sortSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF001D.FILE_BLOB
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private byte[] fileBlob;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.ATTCH_FILE_GRP_ID
     *
     * @return the value of TB_SAF001D.ATTCH_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getAttchFileGrpId() {
        return attchFileGrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.ATTCH_FILE_GRP_ID
     *
     * @param attchFileGrpId the value for TB_SAF001D.ATTCH_FILE_GRP_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setAttchFileGrpId(String attchFileGrpId) {
        this.attchFileGrpId = attchFileGrpId == null ? null : attchFileGrpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.ATTCH_FILE_ID
     *
     * @return the value of TB_SAF001D.ATTCH_FILE_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getAttchFileId() {
        return attchFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.ATTCH_FILE_ID
     *
     * @param attchFileId the value for TB_SAF001D.ATTCH_FILE_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setAttchFileId(String attchFileId) {
        this.attchFileId = attchFileId == null ? null : attchFileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.FILE_NM
     *
     * @return the value of TB_SAF001D.FILE_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getFileNm() {
        return fileNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.FILE_NM
     *
     * @param fileNm the value for TB_SAF001D.FILE_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setFileNm(String fileNm) {
        this.fileNm = fileNm == null ? null : fileNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.FILE_EXT
     *
     * @return the value of TB_SAF001D.FILE_EXT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getFileExt() {
        return fileExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.FILE_EXT
     *
     * @param fileExt the value for TB_SAF001D.FILE_EXT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setFileExt(String fileExt) {
        this.fileExt = fileExt == null ? null : fileExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.FILE_LENTH
     *
     * @return the value of TB_SAF001D.FILE_LENTH
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Long getFileLenth() {
        return fileLenth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.FILE_LENTH
     *
     * @param fileLenth the value for TB_SAF001D.FILE_LENTH
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setFileLenth(Long fileLenth) {
        this.fileLenth = fileLenth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.FILE_PATH
     *
     * @return the value of TB_SAF001D.FILE_PATH
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.FILE_PATH
     *
     * @param filePath the value for TB_SAF001D.FILE_PATH
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.FILE_URL
     *
     * @return the value of TB_SAF001D.FILE_URL
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.FILE_URL
     *
     * @param fileUrl the value for TB_SAF001D.FILE_URL
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.SORT_SN
     *
     * @return the value of TB_SAF001D.SORT_SN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Long getSortSn() {
        return sortSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.SORT_SN
     *
     * @param sortSn the value for TB_SAF001D.SORT_SN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setSortSn(Long sortSn) {
        this.sortSn = sortSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.REGIST_USR_ID
     *
     * @return the value of TB_SAF001D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_SAF001D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(Date registUsrId) {
        this.registUsrId = registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.REGIST_DT
     *
     * @return the value of TB_SAF001D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.REGIST_DT
     *
     * @param registDt the value for TB_SAF001D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(String registDt) {
        this.registDt = registDt == null ? null : registDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.UPDT_ID
     *
     * @return the value of TB_SAF001D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtId() {
        return updtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.UPDT_ID
     *
     * @param updtId the value for TB_SAF001D.UPDT_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtId(Date updtId) {
        this.updtId = updtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.UPDT_DT
     *
     * @return the value of TB_SAF001D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.UPDT_DT
     *
     * @param updtDt the value for TB_SAF001D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(String updtDt) {
        this.updtDt = updtDt == null ? null : updtDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF001D.FILE_BLOB
     *
     * @return the value of TB_SAF001D.FILE_BLOB
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public byte[] getFileBlob() {
        return fileBlob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF001D.FILE_BLOB
     *
     * @param fileBlob the value for TB_SAF001D.FILE_BLOB
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setFileBlob(byte[] fileBlob) {
        this.fileBlob = fileBlob;
    }
}