package com.merck.catalog.admin.model;

import java.util.Date;

public class TbSau001m {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String usrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.PIPA_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String pipaUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.PIPA_TOKEN_VAL
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String pipaTokenVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.PIPA_IF_INFO_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String pipaIfInfo01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.PIPA_IF_INFO_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String pipaIfInfo02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.PIPA_IF_INFO_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String pipaIfInfo03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.USR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String usrNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.DEPT_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String deptCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.DEPT_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String deptNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.PHONE_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.TEL_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.EMAIL_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String emailAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.MANG_USR_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangUsrSeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.OS_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String osId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.OS_VER
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String osVer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.BROWS_INFO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String browsInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.CONN_IP_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String connIpAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.LAST_LOGIN_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date lastLoginDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.LAST_LOGOUT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date lastLogoutDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU001M.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtUsrId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.USR_ID
     *
     * @return the value of TB_SAU001M.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.USR_ID
     *
     * @param usrId the value for TB_SAU001M.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUsrId(String usrId) {
        this.usrId = usrId == null ? null : usrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.PIPA_USR_ID
     *
     * @return the value of TB_SAU001M.PIPA_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPipaUsrId() {
        return pipaUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.PIPA_USR_ID
     *
     * @param pipaUsrId the value for TB_SAU001M.PIPA_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPipaUsrId(String pipaUsrId) {
        this.pipaUsrId = pipaUsrId == null ? null : pipaUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.PIPA_TOKEN_VAL
     *
     * @return the value of TB_SAU001M.PIPA_TOKEN_VAL
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPipaTokenVal() {
        return pipaTokenVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.PIPA_TOKEN_VAL
     *
     * @param pipaTokenVal the value for TB_SAU001M.PIPA_TOKEN_VAL
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPipaTokenVal(String pipaTokenVal) {
        this.pipaTokenVal = pipaTokenVal == null ? null : pipaTokenVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.PIPA_IF_INFO_01
     *
     * @return the value of TB_SAU001M.PIPA_IF_INFO_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPipaIfInfo01() {
        return pipaIfInfo01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.PIPA_IF_INFO_01
     *
     * @param pipaIfInfo01 the value for TB_SAU001M.PIPA_IF_INFO_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPipaIfInfo01(String pipaIfInfo01) {
        this.pipaIfInfo01 = pipaIfInfo01 == null ? null : pipaIfInfo01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.PIPA_IF_INFO_02
     *
     * @return the value of TB_SAU001M.PIPA_IF_INFO_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPipaIfInfo02() {
        return pipaIfInfo02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.PIPA_IF_INFO_02
     *
     * @param pipaIfInfo02 the value for TB_SAU001M.PIPA_IF_INFO_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPipaIfInfo02(String pipaIfInfo02) {
        this.pipaIfInfo02 = pipaIfInfo02 == null ? null : pipaIfInfo02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.PIPA_IF_INFO_03
     *
     * @return the value of TB_SAU001M.PIPA_IF_INFO_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPipaIfInfo03() {
        return pipaIfInfo03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.PIPA_IF_INFO_03
     *
     * @param pipaIfInfo03 the value for TB_SAU001M.PIPA_IF_INFO_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPipaIfInfo03(String pipaIfInfo03) {
        this.pipaIfInfo03 = pipaIfInfo03 == null ? null : pipaIfInfo03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.USR_NM
     *
     * @return the value of TB_SAU001M.USR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUsrNm() {
        return usrNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.USR_NM
     *
     * @param usrNm the value for TB_SAU001M.USR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUsrNm(String usrNm) {
        this.usrNm = usrNm == null ? null : usrNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.PASSWD
     *
     * @return the value of TB_SAU001M.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.PASSWD
     *
     * @param passwd the value for TB_SAU001M.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.DEPT_CD
     *
     * @return the value of TB_SAU001M.DEPT_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getDeptCd() {
        return deptCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.DEPT_CD
     *
     * @param deptCd the value for TB_SAU001M.DEPT_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setDeptCd(String deptCd) {
        this.deptCd = deptCd == null ? null : deptCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.DEPT_NM
     *
     * @return the value of TB_SAU001M.DEPT_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getDeptNm() {
        return deptNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.DEPT_NM
     *
     * @param deptNm the value for TB_SAU001M.DEPT_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setDeptNm(String deptNm) {
        this.deptNm = deptNm == null ? null : deptNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.PHONE_NO
     *
     * @return the value of TB_SAU001M.PHONE_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.PHONE_NO
     *
     * @param phoneNo the value for TB_SAU001M.PHONE_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.TEL_NO
     *
     * @return the value of TB_SAU001M.TEL_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.TEL_NO
     *
     * @param telNo the value for TB_SAU001M.TEL_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo == null ? null : telNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.EMAIL_ADDR
     *
     * @return the value of TB_SAU001M.EMAIL_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getEmailAddr() {
        return emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.EMAIL_ADDR
     *
     * @param emailAddr the value for TB_SAU001M.EMAIL_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr == null ? null : emailAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.MANG_USR_SE_CD
     *
     * @return the value of TB_SAU001M.MANG_USR_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangUsrSeCd() {
        return mangUsrSeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.MANG_USR_SE_CD
     *
     * @param mangUsrSeCd the value for TB_SAU001M.MANG_USR_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangUsrSeCd(String mangUsrSeCd) {
        this.mangUsrSeCd = mangUsrSeCd == null ? null : mangUsrSeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.OS_ID
     *
     * @return the value of TB_SAU001M.OS_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getOsId() {
        return osId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.OS_ID
     *
     * @param osId the value for TB_SAU001M.OS_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setOsId(String osId) {
        this.osId = osId == null ? null : osId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.OS_VER
     *
     * @return the value of TB_SAU001M.OS_VER
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getOsVer() {
        return osVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.OS_VER
     *
     * @param osVer the value for TB_SAU001M.OS_VER
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setOsVer(String osVer) {
        this.osVer = osVer == null ? null : osVer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.BROWS_INFO
     *
     * @return the value of TB_SAU001M.BROWS_INFO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getBrowsInfo() {
        return browsInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.BROWS_INFO
     *
     * @param browsInfo the value for TB_SAU001M.BROWS_INFO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setBrowsInfo(String browsInfo) {
        this.browsInfo = browsInfo == null ? null : browsInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.CONN_IP_ADDR
     *
     * @return the value of TB_SAU001M.CONN_IP_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getConnIpAddr() {
        return connIpAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.CONN_IP_ADDR
     *
     * @param connIpAddr the value for TB_SAU001M.CONN_IP_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setConnIpAddr(String connIpAddr) {
        this.connIpAddr = connIpAddr == null ? null : connIpAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.USE_YN
     *
     * @return the value of TB_SAU001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.USE_YN
     *
     * @param useYn the value for TB_SAU001M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.LAST_LOGIN_DT
     *
     * @return the value of TB_SAU001M.LAST_LOGIN_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getLastLoginDt() {
        return lastLoginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.LAST_LOGIN_DT
     *
     * @param lastLoginDt the value for TB_SAU001M.LAST_LOGIN_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setLastLoginDt(Date lastLoginDt) {
        this.lastLoginDt = lastLoginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.LAST_LOGOUT_DT
     *
     * @return the value of TB_SAU001M.LAST_LOGOUT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getLastLogoutDt() {
        return lastLogoutDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.LAST_LOGOUT_DT
     *
     * @param lastLogoutDt the value for TB_SAU001M.LAST_LOGOUT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setLastLogoutDt(Date lastLogoutDt) {
        this.lastLogoutDt = lastLogoutDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.REGIST_DT
     *
     * @return the value of TB_SAU001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.REGIST_DT
     *
     * @param registDt the value for TB_SAU001M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.REGIST_USR_ID
     *
     * @return the value of TB_SAU001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_SAU001M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.UPDT_DT
     *
     * @return the value of TB_SAU001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.UPDT_DT
     *
     * @param updtDt the value for TB_SAU001M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU001M.UPDT_USR_ID
     *
     * @return the value of TB_SAU001M.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtUsrId() {
        return updtUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU001M.UPDT_USR_ID
     *
     * @param updtUsrId the value for TB_SAU001M.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtUsrId(String updtUsrId) {
        this.updtUsrId = updtUsrId == null ? null : updtUsrId.trim();
    }
}