package com.merck.catalog.admin.model;

import java.util.Date;

public class TbSau002d {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String usrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.UDID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String udid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.OS_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String osId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.OS_VER
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String osVer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.MACHN_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String machnNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.CONN_IP_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String connIpAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.PLATFRM_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String platfrmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.TOKEN_VAL
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String tokenVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.MANG_ITEM_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangItem01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.MANG_ITEM_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangItem02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.MANG_ITEM_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangItem03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.MANG_ITEM_04
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangItem04;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.MANG_ITEM_05
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangItem05;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.LAST_LOGIN_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date lastLoginDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.LAST_LOGOUT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date lastLogoutDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002D.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtUsrId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.USR_ID
     *
     * @return the value of TB_SAU002D.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.USR_ID
     *
     * @param usrId the value for TB_SAU002D.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUsrId(String usrId) {
        this.usrId = usrId == null ? null : usrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.UDID
     *
     * @return the value of TB_SAU002D.UDID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUdid() {
        return udid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.UDID
     *
     * @param udid the value for TB_SAU002D.UDID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUdid(String udid) {
        this.udid = udid == null ? null : udid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.OS_ID
     *
     * @return the value of TB_SAU002D.OS_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getOsId() {
        return osId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.OS_ID
     *
     * @param osId the value for TB_SAU002D.OS_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setOsId(String osId) {
        this.osId = osId == null ? null : osId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.OS_VER
     *
     * @return the value of TB_SAU002D.OS_VER
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getOsVer() {
        return osVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.OS_VER
     *
     * @param osVer the value for TB_SAU002D.OS_VER
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setOsVer(String osVer) {
        this.osVer = osVer == null ? null : osVer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.MACHN_NM
     *
     * @return the value of TB_SAU002D.MACHN_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMachnNm() {
        return machnNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.MACHN_NM
     *
     * @param machnNm the value for TB_SAU002D.MACHN_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMachnNm(String machnNm) {
        this.machnNm = machnNm == null ? null : machnNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.CONN_IP_ADDR
     *
     * @return the value of TB_SAU002D.CONN_IP_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getConnIpAddr() {
        return connIpAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.CONN_IP_ADDR
     *
     * @param connIpAddr the value for TB_SAU002D.CONN_IP_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setConnIpAddr(String connIpAddr) {
        this.connIpAddr = connIpAddr == null ? null : connIpAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.PLATFRM_ID
     *
     * @return the value of TB_SAU002D.PLATFRM_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPlatfrmId() {
        return platfrmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.PLATFRM_ID
     *
     * @param platfrmId the value for TB_SAU002D.PLATFRM_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPlatfrmId(String platfrmId) {
        this.platfrmId = platfrmId == null ? null : platfrmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.TOKEN_VAL
     *
     * @return the value of TB_SAU002D.TOKEN_VAL
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getTokenVal() {
        return tokenVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.TOKEN_VAL
     *
     * @param tokenVal the value for TB_SAU002D.TOKEN_VAL
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setTokenVal(String tokenVal) {
        this.tokenVal = tokenVal == null ? null : tokenVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.MANG_ITEM_01
     *
     * @return the value of TB_SAU002D.MANG_ITEM_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangItem01() {
        return mangItem01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.MANG_ITEM_01
     *
     * @param mangItem01 the value for TB_SAU002D.MANG_ITEM_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangItem01(String mangItem01) {
        this.mangItem01 = mangItem01 == null ? null : mangItem01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.MANG_ITEM_02
     *
     * @return the value of TB_SAU002D.MANG_ITEM_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangItem02() {
        return mangItem02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.MANG_ITEM_02
     *
     * @param mangItem02 the value for TB_SAU002D.MANG_ITEM_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangItem02(String mangItem02) {
        this.mangItem02 = mangItem02 == null ? null : mangItem02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.MANG_ITEM_03
     *
     * @return the value of TB_SAU002D.MANG_ITEM_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangItem03() {
        return mangItem03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.MANG_ITEM_03
     *
     * @param mangItem03 the value for TB_SAU002D.MANG_ITEM_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangItem03(String mangItem03) {
        this.mangItem03 = mangItem03 == null ? null : mangItem03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.MANG_ITEM_04
     *
     * @return the value of TB_SAU002D.MANG_ITEM_04
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangItem04() {
        return mangItem04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.MANG_ITEM_04
     *
     * @param mangItem04 the value for TB_SAU002D.MANG_ITEM_04
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangItem04(String mangItem04) {
        this.mangItem04 = mangItem04 == null ? null : mangItem04.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.MANG_ITEM_05
     *
     * @return the value of TB_SAU002D.MANG_ITEM_05
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangItem05() {
        return mangItem05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.MANG_ITEM_05
     *
     * @param mangItem05 the value for TB_SAU002D.MANG_ITEM_05
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangItem05(String mangItem05) {
        this.mangItem05 = mangItem05 == null ? null : mangItem05.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.USE_YN
     *
     * @return the value of TB_SAU002D.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.USE_YN
     *
     * @param useYn the value for TB_SAU002D.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.LAST_LOGIN_DT
     *
     * @return the value of TB_SAU002D.LAST_LOGIN_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getLastLoginDt() {
        return lastLoginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.LAST_LOGIN_DT
     *
     * @param lastLoginDt the value for TB_SAU002D.LAST_LOGIN_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setLastLoginDt(Date lastLoginDt) {
        this.lastLoginDt = lastLoginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.LAST_LOGOUT_DT
     *
     * @return the value of TB_SAU002D.LAST_LOGOUT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getLastLogoutDt() {
        return lastLogoutDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.LAST_LOGOUT_DT
     *
     * @param lastLogoutDt the value for TB_SAU002D.LAST_LOGOUT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setLastLogoutDt(Date lastLogoutDt) {
        this.lastLogoutDt = lastLogoutDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.REGIST_DT
     *
     * @return the value of TB_SAU002D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.REGIST_DT
     *
     * @param registDt the value for TB_SAU002D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.REGIST_USR_ID
     *
     * @return the value of TB_SAU002D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_SAU002D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.UPDT_DT
     *
     * @return the value of TB_SAU002D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.UPDT_DT
     *
     * @param updtDt the value for TB_SAU002D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002D.UPDT_USR_ID
     *
     * @return the value of TB_SAU002D.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtUsrId() {
        return updtUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002D.UPDT_USR_ID
     *
     * @param updtUsrId the value for TB_SAU002D.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtUsrId(String updtUsrId) {
        this.updtUsrId = updtUsrId == null ? null : updtUsrId.trim();
    }
}