package com.merck.catalog.admin.model;

import java.util.Date;

public class TbSau002m {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String usrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.USR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String usrNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.PHONE_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.TEL_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.EMAIL_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String emailAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.BIRTH_MMDD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String birthMmdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.GENDR_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String gendrSeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.USR_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String usrSeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.LAST_LOGIN_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date lastLoginDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.LAST_LOGOUT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date lastLogoutDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAU002M.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtUsrId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.USR_ID
     *
     * @return the value of TB_SAU002M.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.USR_ID
     *
     * @param usrId the value for TB_SAU002M.USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUsrId(String usrId) {
        this.usrId = usrId == null ? null : usrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.USR_NM
     *
     * @return the value of TB_SAU002M.USR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUsrNm() {
        return usrNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.USR_NM
     *
     * @param usrNm the value for TB_SAU002M.USR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUsrNm(String usrNm) {
        this.usrNm = usrNm == null ? null : usrNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.PASSWD
     *
     * @return the value of TB_SAU002M.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.PASSWD
     *
     * @param passwd the value for TB_SAU002M.PASSWD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.PHONE_NO
     *
     * @return the value of TB_SAU002M.PHONE_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.PHONE_NO
     *
     * @param phoneNo the value for TB_SAU002M.PHONE_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.TEL_NO
     *
     * @return the value of TB_SAU002M.TEL_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.TEL_NO
     *
     * @param telNo the value for TB_SAU002M.TEL_NO
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo == null ? null : telNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.EMAIL_ADDR
     *
     * @return the value of TB_SAU002M.EMAIL_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getEmailAddr() {
        return emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.EMAIL_ADDR
     *
     * @param emailAddr the value for TB_SAU002M.EMAIL_ADDR
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr == null ? null : emailAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.BIRTH_MMDD
     *
     * @return the value of TB_SAU002M.BIRTH_MMDD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getBirthMmdd() {
        return birthMmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.BIRTH_MMDD
     *
     * @param birthMmdd the value for TB_SAU002M.BIRTH_MMDD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setBirthMmdd(String birthMmdd) {
        this.birthMmdd = birthMmdd == null ? null : birthMmdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.GENDR_SE_CD
     *
     * @return the value of TB_SAU002M.GENDR_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getGendrSeCd() {
        return gendrSeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.GENDR_SE_CD
     *
     * @param gendrSeCd the value for TB_SAU002M.GENDR_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setGendrSeCd(String gendrSeCd) {
        this.gendrSeCd = gendrSeCd == null ? null : gendrSeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.USR_SE_CD
     *
     * @return the value of TB_SAU002M.USR_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUsrSeCd() {
        return usrSeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.USR_SE_CD
     *
     * @param usrSeCd the value for TB_SAU002M.USR_SE_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUsrSeCd(String usrSeCd) {
        this.usrSeCd = usrSeCd == null ? null : usrSeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.USE_YN
     *
     * @return the value of TB_SAU002M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.USE_YN
     *
     * @param useYn the value for TB_SAU002M.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.LAST_LOGIN_DT
     *
     * @return the value of TB_SAU002M.LAST_LOGIN_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getLastLoginDt() {
        return lastLoginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.LAST_LOGIN_DT
     *
     * @param lastLoginDt the value for TB_SAU002M.LAST_LOGIN_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setLastLoginDt(Date lastLoginDt) {
        this.lastLoginDt = lastLoginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.LAST_LOGOUT_DT
     *
     * @return the value of TB_SAU002M.LAST_LOGOUT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getLastLogoutDt() {
        return lastLogoutDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.LAST_LOGOUT_DT
     *
     * @param lastLogoutDt the value for TB_SAU002M.LAST_LOGOUT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setLastLogoutDt(Date lastLogoutDt) {
        this.lastLogoutDt = lastLogoutDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.REGIST_DT
     *
     * @return the value of TB_SAU002M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.REGIST_DT
     *
     * @param registDt the value for TB_SAU002M.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.REGIST_USR_ID
     *
     * @return the value of TB_SAU002M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_SAU002M.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.UPDT_DT
     *
     * @return the value of TB_SAU002M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.UPDT_DT
     *
     * @param updtDt the value for TB_SAU002M.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAU002M.UPDT_USR_ID
     *
     * @return the value of TB_SAU002M.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtUsrId() {
        return updtUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAU002M.UPDT_USR_ID
     *
     * @param updtUsrId the value for TB_SAU002M.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtUsrId(String updtUsrId) {
        this.updtUsrId = updtUsrId == null ? null : updtUsrId.trim();
    }
}