package com.merck.catalog.admin.model;

import java.util.Date;

public class TbSaa002d {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.CMMN_CD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String cmmnCdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.CMMN_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String cmmnCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.CMMN_CD_ID_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String cmmnCdIdNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.CMMN_CD_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String cmmnCdNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.CMMN_CD_ABBR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String cmmnCdAbbrNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.CMMN_CD_SN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Long cmmnCdSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.CMMN_SORT_SN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Long cmmnSortSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.MANG_ITEM_PARM_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangItemParm01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.MANG_ITEM_VAL_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangItemVal01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.MANG_ITEM_PARM_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangItemParm02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.MANG_ITEM_VAL_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangItemVal02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.MANG_ITEM_PARM_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangItemParm03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.MANG_ITEM_VAL_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String mangItemVal03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private Date updtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAA002D.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    private String updtUsrId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.CMMN_CD_ID
     *
     * @return the value of TB_SAA002D.CMMN_CD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCmmnCdId() {
        return cmmnCdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.CMMN_CD_ID
     *
     * @param cmmnCdId the value for TB_SAA002D.CMMN_CD_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCmmnCdId(String cmmnCdId) {
        this.cmmnCdId = cmmnCdId == null ? null : cmmnCdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.CMMN_CD
     *
     * @return the value of TB_SAA002D.CMMN_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCmmnCd() {
        return cmmnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.CMMN_CD
     *
     * @param cmmnCd the value for TB_SAA002D.CMMN_CD
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCmmnCd(String cmmnCd) {
        this.cmmnCd = cmmnCd == null ? null : cmmnCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.CMMN_CD_ID_NM
     *
     * @return the value of TB_SAA002D.CMMN_CD_ID_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCmmnCdIdNm() {
        return cmmnCdIdNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.CMMN_CD_ID_NM
     *
     * @param cmmnCdIdNm the value for TB_SAA002D.CMMN_CD_ID_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCmmnCdIdNm(String cmmnCdIdNm) {
        this.cmmnCdIdNm = cmmnCdIdNm == null ? null : cmmnCdIdNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.CMMN_CD_NM
     *
     * @return the value of TB_SAA002D.CMMN_CD_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCmmnCdNm() {
        return cmmnCdNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.CMMN_CD_NM
     *
     * @param cmmnCdNm the value for TB_SAA002D.CMMN_CD_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCmmnCdNm(String cmmnCdNm) {
        this.cmmnCdNm = cmmnCdNm == null ? null : cmmnCdNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.CMMN_CD_ABBR_NM
     *
     * @return the value of TB_SAA002D.CMMN_CD_ABBR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getCmmnCdAbbrNm() {
        return cmmnCdAbbrNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.CMMN_CD_ABBR_NM
     *
     * @param cmmnCdAbbrNm the value for TB_SAA002D.CMMN_CD_ABBR_NM
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCmmnCdAbbrNm(String cmmnCdAbbrNm) {
        this.cmmnCdAbbrNm = cmmnCdAbbrNm == null ? null : cmmnCdAbbrNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.CMMN_CD_SN
     *
     * @return the value of TB_SAA002D.CMMN_CD_SN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Long getCmmnCdSn() {
        return cmmnCdSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.CMMN_CD_SN
     *
     * @param cmmnCdSn the value for TB_SAA002D.CMMN_CD_SN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCmmnCdSn(Long cmmnCdSn) {
        this.cmmnCdSn = cmmnCdSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.CMMN_SORT_SN
     *
     * @return the value of TB_SAA002D.CMMN_SORT_SN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Long getCmmnSortSn() {
        return cmmnSortSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.CMMN_SORT_SN
     *
     * @param cmmnSortSn the value for TB_SAA002D.CMMN_SORT_SN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setCmmnSortSn(Long cmmnSortSn) {
        this.cmmnSortSn = cmmnSortSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.MANG_ITEM_PARM_01
     *
     * @return the value of TB_SAA002D.MANG_ITEM_PARM_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangItemParm01() {
        return mangItemParm01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.MANG_ITEM_PARM_01
     *
     * @param mangItemParm01 the value for TB_SAA002D.MANG_ITEM_PARM_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangItemParm01(String mangItemParm01) {
        this.mangItemParm01 = mangItemParm01 == null ? null : mangItemParm01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.MANG_ITEM_VAL_01
     *
     * @return the value of TB_SAA002D.MANG_ITEM_VAL_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangItemVal01() {
        return mangItemVal01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.MANG_ITEM_VAL_01
     *
     * @param mangItemVal01 the value for TB_SAA002D.MANG_ITEM_VAL_01
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangItemVal01(String mangItemVal01) {
        this.mangItemVal01 = mangItemVal01 == null ? null : mangItemVal01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.MANG_ITEM_PARM_02
     *
     * @return the value of TB_SAA002D.MANG_ITEM_PARM_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangItemParm02() {
        return mangItemParm02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.MANG_ITEM_PARM_02
     *
     * @param mangItemParm02 the value for TB_SAA002D.MANG_ITEM_PARM_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangItemParm02(String mangItemParm02) {
        this.mangItemParm02 = mangItemParm02 == null ? null : mangItemParm02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.MANG_ITEM_VAL_02
     *
     * @return the value of TB_SAA002D.MANG_ITEM_VAL_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangItemVal02() {
        return mangItemVal02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.MANG_ITEM_VAL_02
     *
     * @param mangItemVal02 the value for TB_SAA002D.MANG_ITEM_VAL_02
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangItemVal02(String mangItemVal02) {
        this.mangItemVal02 = mangItemVal02 == null ? null : mangItemVal02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.MANG_ITEM_PARM_03
     *
     * @return the value of TB_SAA002D.MANG_ITEM_PARM_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangItemParm03() {
        return mangItemParm03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.MANG_ITEM_PARM_03
     *
     * @param mangItemParm03 the value for TB_SAA002D.MANG_ITEM_PARM_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangItemParm03(String mangItemParm03) {
        this.mangItemParm03 = mangItemParm03 == null ? null : mangItemParm03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.MANG_ITEM_VAL_03
     *
     * @return the value of TB_SAA002D.MANG_ITEM_VAL_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getMangItemVal03() {
        return mangItemVal03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.MANG_ITEM_VAL_03
     *
     * @param mangItemVal03 the value for TB_SAA002D.MANG_ITEM_VAL_03
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setMangItemVal03(String mangItemVal03) {
        this.mangItemVal03 = mangItemVal03 == null ? null : mangItemVal03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.USE_YN
     *
     * @return the value of TB_SAA002D.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.USE_YN
     *
     * @param useYn the value for TB_SAA002D.USE_YN
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.REGIST_DT
     *
     * @return the value of TB_SAA002D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.REGIST_DT
     *
     * @param registDt the value for TB_SAA002D.REGIST_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.REGIST_USR_ID
     *
     * @return the value of TB_SAA002D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_SAA002D.REGIST_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.UPDT_DT
     *
     * @return the value of TB_SAA002D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.UPDT_DT
     *
     * @param updtDt the value for TB_SAA002D.UPDT_DT
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAA002D.UPDT_USR_ID
     *
     * @return the value of TB_SAA002D.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public String getUpdtUsrId() {
        return updtUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAA002D.UPDT_USR_ID
     *
     * @param updtUsrId the value for TB_SAA002D.UPDT_USR_ID
     *
     * @mbg.generated Tue Jul 20 01:54:32 KST 2021
     */
    public void setUpdtUsrId(String updtUsrId) {
        this.updtUsrId = updtUsrId == null ? null : updtUsrId.trim();
    }
}